FROM node:22-bookworm

WORKDIR /usr/src/app/frontend

ENV PATH /usr/src/app/frontend/node_modules/.bin:$PATH

COPY package.json .
RUN npm install
RUN npx next telemetry disable

CMD ["npm", "run", "dev"]
