FROM node:22-slim

WORKDIR /usr/src/app/frontend

ENV PATH /usr/src/app/frontend/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm ci
RUN npx next telemetry disable

COPY . .
RUN npm run build

CMD ["npm", "run", "start"]
