version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/static:/var/www/static
      - ./nginx/media:/var/www/media
    networks:
      - frontend
      - backend

  django:
    container_name: django
    build:
      context: ./backend
    stdin_open: true
    restart: always
    volumes:
      - ./backend:/usr/src/app
    env_file: ./backend/.env
    networks:
      - backend
      - frontend

  nextjs:
    container_name: nextjs
    build: 
      context: ./frontend
    stdin_open: true
    restart: always
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file: ./frontend/.env
    networks:
      - backend
      - frontend

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    volumes:
      - ./nginx/db:/var/lib/postgresql/data
    env_file: ./nginx/.env
    networks:
      - backend

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - frontend

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
