version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/static:/var/www/static
      - ./nginx/media:/var/www/media
    networks:
      - frontend
      - backend

  django:
    container_name: django
    build:
      context: ./backend
    stdin_open: true
    restart: always
    volumes:
      - ./backend:/usr/src/app/backend
    environment:
      - SECRET_KEY=123
      - DEBUG=1
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=pguser
      - SQL_PASSWORD=pgpassword
      - SQL_HOST=postgres
    networks:
      - backend
      - frontend

  nextjs:
    container_name: nextjs
    build: 
      context: ./frontend
    stdin_open: true
    restart: always
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - backend
      - frontend

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    volumes:
      - ./nginx/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=postgres
    networks:
      - backend

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - frontend

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
