FROM python:latest

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN python -m pip install --upgrade pip
COPY ./requirements.txt .
RUN python -m pip install -r requirements.txt

COPY . .

#RUN python manage.py collectstatic
#RUN python manage.py makemigrations
#RUN python manage.py migrate

CMD ["python", "manage.py", "runserver"]
